#!/bin/sh
git add git-commit .gitignore gitd Make.sh scripts src README run* install-*
TZ=UTC git commit --date="`date -u +'%s'`"
test -x /usr/lib/git-core/git-update-server-info && /usr/lib/git-core/git-update-server-info
