#!/bin/sh -e

export INTERFACE=`cat env/INTERFACE`
export TUN_ADDR=`cat env/TUN_ADDR`
export GATEWAY=`cat env/GATEWAY`
export PTP=`cat env/PTP`
export LOCALIP=`cat env/LOCALIP`
export LOCALPORT=`cat env/LOCALPORT`
export REMOTEIP=`cat env/REMOTEIP`
export REMOTEPORT=`cat env/REMOTEPORT`
export PUBKEY=`cat env/PUBKEY`
export MTU=`cat env/MTU`
export PROTOCOL=`cat env/PROTOCOL 2>/dev/null` || :
#export USE_PI=`cat env/USE_PI 2>/dev/null` || :
#[ -z $USE_PI ] && unset USE_PI

(
  sleep 4
  if which ip; then
    ip addr add $TUN_ADDR peer $PTP/32 dev $INTERFACE scope link
    ip addr add $GATEWAY/32 dev $INTERFACE scope global
    ip link set dev $INTERFACE up
    ifconfig $INTERFACE mtu $MTU
  else
    ifconfig $INTERFACE create $TUN_ADDR $PTP netmask 255.255.255.255 mtu $MTU up
    route add -host $PTP -link $INTERFACE -iface &
  fi
  ping -c 16 -I $INTERFACE $PTP -r -w 8
) &

ignchld=''
test -x ignchld && ignchild='./ignchld'
exec $ignchld ./cryptotun$PROTOCOL $LOCALIP $LOCALPORT $REMOTEIP $REMOTEPORT env/SECKEY $PUBKEY $INTERFACE
