#!/bin/sh -e
[ -z $9 ] && echo $0' <local ip> <local port> <remote ip> <remote port> <interface> <tap addr w/ subnet> <gateway> <broadcast> <pubkey>' 2>&1 && \
  exit 64

mkdir -p /services/cryptotap-$5/ || exit 255
mkdir -p /services/cryptotap-$5/env || exit 255

head -c 32 /dev/urandom > /services/cryptotap-$5/env/SECKEY || exit 255

printf 1024 > /services/cryptotap-$5/env/MTU || exit 255

printf $1 > /services/cryptotap-$5/env/LOCALIP || exit 255
printf $2 > /services/cryptotap-$5/env/LOCALPORT || exit 255
printf $3 > /services/cryptotap-$5/env/REMOTEIP || exit 255
printf $4 > /services/cryptotap-$5/env/REMOTEPORT || exit 255
printf $5 > /services/cryptotap-$5/env/INTERFACE || exit 255
printf $6 > /services/cryptotap-$5/env/TAP_ADDR || exit 255
printf $7 > /services/cryptotap-$5/env/GATEWAY || exit 255
printf $8 > /services/cryptotap-$5/env/BRD || exit 255
printf $9 > /services/cryptotap-$5/env/PUBKEY || exit 255

chmod 700 /services/cryptotap-$5/env/ || exit 255

test -L /services/cryptotap-$5/cryptotun || \
  ln -s "`pwd`"/cryptotun /services/cryptotap-$5/cryptotun || exit 255

cp run.tap /services/cryptotap-$5/run || exit 255

test -L /services/cryptotap-$5/ || \
  ln -s /services/cryptotap-$5/ /service/cryptotap-$5 || exit 255

./pubkey /services/cryptotap-$5/env/SECKEY
