#!/bin/sh -e
[ -z $9 ] && echo $0' <local ip> <local port> <remote ip> <remote port> <interface> <tun addr> <gateway> <ptp> <remote pubkey>' 2>&1 && \
  exit 64

mkdir -p /services/cryptotun-$5/ || exit 255
mkdir -p /services/cryptotun-$5/env || exit 255

head -c 32 /dev/urandom > /services/cryptotun-$5/env/SECKEY || exit 255

printf 1360 > /services/cryptotun-$5/env/MTU || exit 255

printf $1 > /services/cryptotun-$5/env/LOCALIP || exit 255
printf $2 > /services/cryptotun-$5/env/LOCALPORT || exit 255
printf $3 > /services/cryptotun-$5/env/REMOTEIP || exit 255
printf $4 > /services/cryptotun-$5/env/REMOTEPORT || exit 255
printf $5 > /services/cryptotun-$5/env/INTERFACE || exit 255
printf $6 > /services/cryptotun-$5/env/TUN_ADDR || exit 255
printf $7 > /services/cryptotun-$5/env/GATEWAY || exit 255
printf $8 > /services/cryptotun-$5/env/PTP || exit 255
printf $9 > /services/cryptotun-$5/env/PUBKEY || exit 255

chmod 700 /services/cryptotun-$5/env/ || exit 255

test -L /services/cryptotun-$5/cryptotun || \
  ln -s "`pwd`"/cryptotun /services/cryptotun-$5/cryptotun || exit 255

cp run /services/cryptotun-$5/run || exit 255

test -L /service/cryptotun-$5/ || \
  ln -s /services/cryptotun-$5/ /service/cryptotun-$5 || exit 255

./pubkey /services/cryptotun-$5/env/SECKEY
